name = "denemeler"
main = "src/index.js"
compatibility_date = "2025-04-24"
workers_dev = true

[env.production]
bindings = [
  { name = "GH_TOKEN", type = "secret" }
]

kv_namespaces = [
  { binding = "TOKENS_DB", id = "a65df4015e4b483fa5fa8f68525582be" }
]
